name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest

      - name: Deploy to VM
        if: success()
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -t -i private_key.pem $VM_USER@$VM_HOST << 'EOF'
            cd /home/azureuser/projects
            if [ ! -d ".git" ]; then
              git init
            fi
            if ! git remote | grep -q origin; then
              git remote add origin https://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@github.com/developer-ahmed-shehta/CI-CD.git
            fi
            git fetch origin
            git reset --hard origin/main
            ls
          EOF
